- Cargo.toml
- igvm/src/hv_defs.rs
- igvm/src/lib.rs
- igvm/src/page_table.rs
- igvm/src/snp_defs.rs
- igvm_defs/src/lib.rs
This update is necessary to work with latest cloud-hypervisor. Cloud-hypervisor uses latest version of zerocopy that gives build issues with the older version of zerocopy used in igvm crate.
> Update zerocopy to latest released version

- igvm/src/lib.rs
Renames the SnpPolicy header to refer to any type of guest isolation.
> Rename Policy header

- Cargo.toml
> Cargo.toml: Bump open-enum to latest version

- igvm_defs/src/lib.rs
Add meaning for the flags field in the IGVM_VHS_MEMORY_MAP_ENTRY structure
> Add definition for flags in IGVM_VHS_MEMORY_MAP_ENTRY

- igvm_defs/src/dt.rs
Add the flags type for memory entries that are exposed via device tree, to match type. Finishes #9.
> igvm_defs: define flags property for device tree

- Cargo.toml
Zerocopy dependency in the root of the workspace is causing alloc to be pulled in on no_std builds. Remove it to allow igvm_defs to be use in no_std without alloc.
> workspace: fix default workspace zerocopy feature pulling in alloc on no_std

- igvm/src/snp_defs.rs
- igvm_defs/src/lib.rs
This tells the host loader to import the page as shared, which makes the data available to the guest but not part of the launch measurement, assuming the host loader is well behaved. 
Also fix a typo in snp_defs.
> igvm_defs: define the shared bit for IgvmPageDataFlags

- igvm/src/snp_defs.rs
- igvm_defs/src/lib.rs
Remove the shared memory state flag from the memory map, since it will not be used.
Add a new variable header for a parameter that describes the default state of memory in the memory map
> Update memory map flag parameters

- igvm/src/lib.rs
- igvm/src/snp_defs.rs
- igvm_defs/src/lib.rs
The IGVM_VHT_ENVIRONMENT_INFO_PARAMETER defines a bitfield that permits the hosting environment to describe certain behaviors so the VM can conform.  The only currently defined behavior indicates whether the default state of memory is assigned (private) or unassigned (shared) so the VM knows whether it must request page state changes before using any memory.  Other behaviors will be defined in the future.
> Define a new variable header type for environment information

- igvm/src/snp_defs.rs
The visibility of all members in the structures defined in snp_defs.rs should be public allowing direct access to the fields within the structures. This was not true for `SevXmmRegister`.
This commit makes the fields in the structure public.
> igvm: Fix visibility of SevXmmRegister members

- igvm/src/hv_defs.rs
- igvm/src/lib.rs
- igvm/src/page_table.rs
- igvm/src/parsing.rs
- igvm/src/registers.rs
- igvm/src/snp_defs.rs
- igvm_defs/src/dt.rs
- igvm_defs/src/lib.rs
> igvm, igvm_defs: Move to SPDX License identifier

- Cargo.toml
Update to the latest version not yanked so we can publish to crates.io.
> deps: update zerocopy due to previous release being yanked

- igvm/src/snp_defs.rs
- igvm_defs/src/dt.rs
- igvm_defs/src/lib.rs
PR #17 meant to revert PR #8 and PR #11 but instead reverted PR #14 incorrectly. 
Fix this by reapplying PR #14 and correctly reverting PR #8 and PR #11.
> igvm_defs: fix incorrect revert of IgvmPageDataFlags instead of MemoryMapEntryFlags

- igvm/src/snp_defs.rs
There is some C code that is currently set up as ignored doctests. These will show up when running `cargo test`. Simply declare them as non-Rust code.
> igvm/snp_defs: do not mark C code as doctests

- Cargo.toml
- igvm/Cargo.toml
`hex` by default is built for std. If other no_std crates include `igvm` as a dependency, during the build Cargo enables features incrementally, thus leaving "std" enabled.
Let's disable `hex` default features, so if other no_std crates include `igvm` as a dependency they can be built without errors.
> workspace: disable default features for `hex`

- igvm/src/lib.rs
- igvm_defs/src/lib.rs
This defines a "native" platform for non-isolated VMs, as well as a VP start context for the x86-64 architecture.
Implements #37.
> igvm_defs: define NATIVE platform

- igvm/src/lib.rs
- igvm_defs/src/lib.rs
This change fixes multiple issues with generating IGVM files that target the NATIVE platform type from #39. 
Part of #37.
> igvm: fix issues with use of NATIVE platform

- Cargo.toml
- igvm/Cargo.toml
- igvm_defs/Cargo.toml
Rev the minor version as this is a breaking change. The breaking change is due to #44 changing the function signature of `write_binary_data` to support file data deduplication.
> release: release version 0.2.0

- igvm_c/Makefile
Some small improvements for the Makefile in igvm_c:
- Recognize the `DESTDIR` variable for staged installs
- Install the `dump_igvm` tool too
> igvm_c: update makefile with DESTDIR and install dump_igvm

- igvm_defs/src/lib.rs
The x86 architecture defines these concepts as "limit" since they do not actually represent the number of bytes in the tables, so the structure names should match.
> Rename IDT/GDT "base" fields to "limit"

- igvm/src/snp_defs.rs
Add several missing bits for `SevFeatures`:
* bit 8: VMPL Supervisor Shadow Stack (VmplSSS).
* bit 9: Secure TSC (SecureTscEn).
* bit 14: VMSA Register Protection (VmsaRegProt).
* bit 15: SMT Protection (SmtProtection).
> snp_defs: add missing fields for `SevFeatures`

- igvm/src/lib.rs
- igvm_defs/src/lib.rs
Add support for aarch64 relocations.
This does not support actually performing the relocations via pagetable fixups, but supports generating IGVM files targeting AArch64 with relocation headers. A future change will add support to the pagetable builder to handle this. 
#58
> Add support for aarch64 relocations.

- Cargo.toml
- igvm/Cargo.toml
- igvm_defs/Cargo.toml
New release that adds preliminary support for AArch64 relocation headers.
> release: release version 0.3.1

- igvm/src/lib.rs
- igvm_defs/src/lib.rs
Currently, only SEV-SNP is supported as a platform type for SEV guests. However, there is no reason why IGVM cannot be used to configure both SEV and SEV-ES.
This commit adds two new platform types: `IgvmPlatformType::SEV` and `IgvmPlatformType::SEV_ES` which allow IGVM files to specifically target these isolation technologies.
Unlike SEV, SEV-ES allows the VP context to be specified. The structure for defining the context is binary compatible with SEV-SNP, therefore the SEV-ES platform type reuses IgvmDirectiveHeader::SnpVpContext to define the VMSA.
> igvm: Add SEV and SEV_ES platform types

- Cargo.toml
Update these dependencies to the latest versions from crates.io:
- bitfield-struct to 0.6.2
- open-enum to 0.5.1
This helps reduce duplicates due to different crate versions in the dependency
trees of consuming projects (for example Coconut-SVSM).
> deps: update bitfield-struct and open-enum

- Cargo.toml
Pickup the dependency fix that fixes #63.
> deps: update open-enum with fix for cfg derives

- .github/workflows/rust.yml
This will fail until the open-enum fix is applied, but will help catch any similar issues with the unstable feature in the future. 
#63
> ci: run clippy pass on igvm_defs with no features

- igvm_defs/src/lib.rs
This PR adds a MemoryMapEntryType for specific purpose memory. This corresponds with the UEFI memory map attribute EFI_MEMORY_SP, added in UEFI 2.8. EFI_MEMORY_SP is used to indicate that the memory has special properties and is to be reserved for application use, and shouldn't be used by the firmware or OS.
> igvm_defs: add support for specific purpose memory in MemoryMapEntryType.

- igvm_defs/src/lib.rs
Seems that this became a new clippy error in 1.80. Fix it.
> clippy: fix new clippy lint around markdown lists

- igvm/src/c_api.rs
Clippy suggests removing the needless lifetime.
> igvm: remove unused lifetime

- igvm_defs/src/lib.rs
Introduce the HIDDEN memory type to describe memory that is visible only through the IGVM memory map.
> igvm_defs: define HIDDEN memory type

- igvm/src/lib.rs
Adds test that the SnpVpContext/IGVM_VHS_VP_CONTEXT/IGVM_VHT_VP_CONTEXT type is serialized and deserialized correctly.
Adds regression test for #80 (compiler bug, so no code changes needed to fix).
> Add test for SnpVpContext

- igvm_c/Makefile
When building using `make -jN` make returns `No rule to make target` for include/igvm.h
Writing the full path fixes the issue.
> igvm_c/Makefile: Fix dependency path

- igvm/src/lib.rs
Fix new clippy lints introduced in 1.86.
> igvm: fix 1.86 clippy lints

- igvm_c/Makefile
This PR adds two optional external parameters: 
- `TARGET_DIR`: can be used to configure the target directory (currently it's `target_c`).
- `EXTRA_PARAMS`: can be used to set some additional parameters for cargo, like a compiler profile.
> igvm_c/Makefile: add two new external parameters

- .github/workflows/rust.yml
Pin the toolchain used in CI to a well known version, so new clippy lints in new versions don't break CI. 
Closes #75
> ci: pin toolchain version to 1.86.0

- igvm_c/Makefile
When cross-compiling with `CARGO_BUILD_TARGET`, the build output path changes to include the target triple (e.g., `target/<triple>/release/`).
This leads to compilation errors as `TARGET_PATH` does not take that into account.
Update `TARGET_PATH` to include the target triple if set.
> igvm_c/Makefile: fix path for cross compilation

- Cargo.toml
- igvm/Cargo.toml
- igvm_defs/Cargo.toml
Update dependencies (notably zerocopy to 0.8.0).
Pickup various igvm_c fixes and improvements.
> release: release version 0.4.0

- igvm_c/Makefile
The `test` and `igvm.bin` targets failed when the `EXE` variable was set as they lacked the EXE suffix.
Append the `EXE` suffix to the `test_data` and `igvm_test` binaries.
> igvm_c/Makefile: Fix test execution when using an EXE suffix
